export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  FROM = "from",
  TO = "to",
  FROMLOC = "fromloc",
  TOLOC="toloc",
  FINDLOC = "findloc",
  ROUTING="routing",

  FINDBUS="findbus",
  ONLPAYMENT="onlpayment",
  TRAVEL="travel",
  FEEDBACKS="feedbacks",
  WEATHER="weather",
  COMMUNITY="community",
  SWITCHBOARD="switchboard",

  USERNAME="username",
  PASSWORD="password",
  FULLNAME="fullname",
  AGE="age",
  ADDRESS="address",
  EMAIL="email",
  LOGOUT="logout",
  LOGIN="login",
  NULL="null",
}
