export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  FROM = "from",
  TO = "to",
  FROMLOC = "fromloc",
  TOLOC="toloc",
  FINDLOC = "findloc",
  ROUTING="routing",

  FINDBUS="findbus",
  ONLPAYMENT="onlpayment",
  BUSFORCOMPANY="busforcompany",
  FEEDBACKS="feedbacks",
  WEATHER="weather",
  COMMUNITY="community",
  SWITCHBOARD="switchboard",

  USERNAME="username",
  PASSWORD="password",
  FULLNAME="fullname",
  AGE="age",
  EMAIL="email",
  LOGOUT="logout",
  LOGIN="login",
  NULL="null",
  FINDSTATION="findstation",
  SEARCHHISTORY="searchhistory",
  RECLOC  = "recently location",
  ADDRESS = "address",
  PICKMAP = "pick on map",
  CHOOSE = "choose",
  ROUTES = "routes",
  BACK = "back"
}
